In [2]:
## Download the analysis result files produced by the workflow genomic in ABRomics

# Definition of the API (swagger): https://analysis.abromics.fr/api/schema/swagger

In [1]:
## imports
from dotenv import load_dotenv # to read the environment variables from the .env file
import os
import requests
import json
import pandas as pd

from rdflib import Graph
import uuid
from rdflib import Namespace
from rdflib import FOAF, DCTERMS, SKOS, VANN, TIME, RDF, RDFS, XSD, OWL, Literal

In [2]:
## env variables
load_dotenv() #! when the .env values change there is no reload it takes the old value... 

## load the environment variables
api_url = os.getenv('API_URL') #! not the right value..
api_username = os.getenv('API_USERNAME')
api_password = os.getenv('API_PASSWORD')
api_temp_basic_token = os.getenv('API_TEMP_BASIC_TOKEN') # will be changed at one point find a way to get a new token via a login with creds

In [3]:
## Objective: Getting all the file results for by analysis for each analysis that worked (aka status:ready_to_report)

# Finding the ids of all the analysis that worked
# Loading the file associated with one analysis that worked

################# Issues : the endpoint doesn't load correctly from the .env file
# 
# endpoint = f"{api_url}/api/analysis/"
# print(endpoint)
# print(api_temp_bearer_token)
#

In [3]:
response = requests.get(
    "https://analysis.abromics.fr/api/analysis/",
    params={'status': 'ready_to_report'},
    headers = {
        'Authorization': f"Basic {api_temp_basic_token}",
    }
)
exploitable_analysis = response.json()
exploitable_analysis_ids = [analysis["id"] for analysis in exploitable_analysis]
exploitable_analysis_ids

[47, 54, 48, 42, 27, 50, 29, 43, 51, 44, 28, 45, 55, 71, 81, 91]

In [7]:
# Finding the report related to one exploitable analysis (ex: analysis with id 40)

In [4]:
#! the bearer token will expire at one point
response = requests.get(
    "https://analysis.abromics.fr/api/report/",
    params={'id': 40},
    headers = {
        'Authorization': f"Basic {api_temp_basic_token}",
    }
)
reports = response.json()

# save the reports in a local file
with open('reports.json', 'w') as f:
    json.dump(reports, f)

In [5]:
reports_names = [report["title"] for report in reports]
print(reports_names) ## Looks like duplicated reports bundle in one report from the database (data are different so no duplication)
print(len(reports_names)) ## 73 Genomic report => maybe one for each strain of bacteria found ?

['GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT', 'GENOMIC RESULT REPORT']
72

In [6]:
[print(section["title"]) for section in reports[0]["sections"]]

SAMPLE SUMMARY
ANALYSIS SUMMARY
 ANTIMICROBIAL RESISTANCE ANALYSES
ORGANISM IDENTIFICATION
QUALITY METRICS
QUALITY ASSEMBLY

[None, None, None, None, None, None]

In [7]:
[print(data) for data in reports[0]["sections"][0]["data"]] ## corespond to the metadata of the sample

{'type': 'summary', 'header': ['Sample ID', 'Microorganism scientific name', 'Collected at', 'Sample source', 'Sample type', 'Host', 'Location', 'Sequencing Technology', 'Sequencing Platform', 'Submitter name', 'Submitter email'], 'values': [None, 'Achromobacter xylosoxidans', None, 'Other', 'environmental', 'Other', None, '454 GS 20', '454', 'Admin Abromics', 'admin@analysis.abromics.fr']}

[None]

In [8]:
[print(data) for data in reports[0]["sections"][1]["data"]] ## corespond to "ANALYSIS SUMMARY"

{'type': 'summary', 'header': ['Isolate identified as', 'ST', 'Number of acquired genes resistances with known target antibiotics'], 'values': ['Pseudomonas aeruginosa', 235, 10]}
{'type': 'list', 'title': 'List of target antibiotics', 'values': [['streptomycin', 'gentamicin', 'kanamycin', 'ampicillin', 'ampicillin,amoxicillin/clavulanicacid,cefoxitin,ceftriaxone', 'chloramphenicol', 'ciprofloxacinI/R', 'fosfomycin', 'unknown[qacE_1_X68232]', 'sulfisoxazole']]}

[None, None]

In [9]:
[print(data) for data in reports[0]["sections"][2]["data"]] ## corespond to "ANTIMICROBIAL RESISTANCE ANALYSIS"

{'type': 'table', 'title': 'Acquired resistance genes', 'header': ['Resistance gene', 'Gene length', 'Identity %', 'Coverage %', 'Contig', 'Start in contig', 'End in contig', 'Strand', 'Target antibiotic', 'Accession number'], 'values': [['aadA13', "ant(2'')-Ia", "aph(3')-IIb", 'blaOXA-488', 'blaPAO', 'catB7', 'crpP', 'fosA', 'qacE', 'sul1'], [798, 534, 807, 789, 1194, 639, 198, 408, 278, 840], [100.0, 100.0, 98.76, 99.87, 99.25, 98.75, 98.48, 99.02, 100.0, 100.0], [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 83.48, 100.0], ['contig00086', 'contig00102', 'contig00001', 'contig00039', 'contig00001', 'contig00033', 'contig00056', 'contig00009', 'contig00139', 'contig00080'], [133, 133, 169523, 19349, 182685, 25811, 3829, 183999, 1, 733], [930, 666, 170329, 20137, 183878, 26449, 4026, 184406, 278, 1572], ['-', '-', '+', '+', '-', '+', '+', '+', '-', '-'], ['streptomycin', 'gentamicin', 'kanamycin', 'ampicillin', 'ampicillin,amoxicillin/clavulanicacid,cefoxitin,ceftriaxone', 'chloramphenicol', 'ciprofloxacinI/R', 'fosfomycin', 'unknown[qacE_1_X68232]', 'sulfisoxazole'], ['AY713504', 'X04555', 'CP006832', 'CP017969', 'AY083592', 'AF036933', 'HM560971', 'ACWU01000146', 'X68232', 'U12338']]}
{'type': 'table', 'title': 'Virulence genes', 'header': ['Virulence gene', 'Gene length', 'Identity %', 'Coverage %', 'Contig', 'Start in contig', 'End in contig', 'Strand', 'Target antibiotic', 'Accession number'], 'values': [['phzM', 'mucE', 'pilF', 'lasB', 'mucP', 'xcpZ', 'xcpY', 'xcpX', 'xcpW', 'xcpV', 'xcpU', 'xcpT', 'xcpS', 'xcpR', 'xcpP', 'xcpQ', 'fimV', 'pilT', 'pilU', 'pilG', 'pilH', 'pilI', 'pilJ', 'pilK', 'chpA', 'chpB', 'chpC', 'chpD', 'chpE', 'algW', 'pilB', 'xcpA/pilD', 'exoY', 'motB', 'motA', 'waaA', 'waaP', 'waaG', 'waaC', 'waaF', 'pilQ', 'pilP', 'pilO', 'pilN', 'pilM', 'vgrG1b', 'vgrG1a', 'clpV1', 'hsiH1', 'hsiG1', 'hsiF1', 'hsiE1', 'hcp1', 'hsiC1/vipB', 'hsiB1/vipA', 'hsiA1', 'fha1', 'lip1', 'hsiJ1', 'dotU1', 'icmF1/tssM1', 'tagF/pppB', 'pppA', 'ppkA', 'tagT', 'tagS', 'tagR', 'tagQ', 'phzH', 'exoT', 'exoU', 'flgB', 'flgC', 'flgD', 'flgE', 'flgF', 'flgG', 'flgH', 'flgI', 'flgJ', 'flgK', 'fleQ', 'fleS', 'fleR', 'fliE', 'fliF', 'fliG', 'fliH', 'fliI', 'fliJ', 'rhlC', 'toxA', 'tse2', 'algU', 'mucA', 'mucB', 'mucC', 'mucD', 'motD', 'motC', 'fliA', 'fleN', 'flhF', 'flhA', 'flhB', 'fliR', 'fliQ', 'fliP', 'fliO', 'fliN', 'fliM', 'fliL', 'fliK', 'lasI', 'aprA', 'plcH', 'phzB1', 'phzA1', 'lasA', 'tse1', 'phzG1', 'algB', 'pilE', 'pilY2', 'pilY1', 'pilX', 'pilW', 'pilV', 'fimU', 'fimT', 'pilR', 'pilS', 'pvdH', 'mbtH-like', 'pvdF', 'pvdO', 'pvdN', 'pvdM', 'pvdP', 'pvdA', 'pvdQ', 'rhlI', 'rhlB', 'rhlA', 'tse3', 'algC', 'pscL', 'pscK', 'pscJ', 'pscI', 'pscH', 'pscG', 'pscF', 'pscE', 'pscD', 'pscC', 'pscB', 'exsD', 'exsA', 'exsB', 'exsE', 'exsC', 'popD', 'popB', 'pcrH', 'pcrV', 'pcrG', 'pcrR', 'pcrD', 'pcr4', 'pcr3', 'pcr2', 'pcr1', 'popN', 'pscN', 'pscO', 'pscP', 'pscQ', 'pscR', 'pscS', 'pscT', 'pscU', 'algZ', 'algR', 'algQ', 'algP/algR3', 'pvcA', 'pvcB', 'pvcC', 'pvcD', 'ptxR', 'algA', 'algF', 'algJ', 'algI', 'algL', 'algX', 'algG', 'algE', 'algK', 'alg44', 'alg8', 'algD', 'motY', 'pchA', 'pchB', 'pchC', 'pchD', 'pchR', 'pchE', 'pchF', 'pchG', 'pchH', 'pchI', 'fptA', 'phzS', 'pvdS', 'pvdG', 'pvdL', 'flgN', 'flgM', 'flgA'], [1005, 270, 759, 1497, 1353, 525, 1149, 1002, 714, 390, 519, 447, 1218, 1509, 708, 1977, 2760, 1035, 1149, 408, 366, 537, 2049, 876, 7419, 1032, 507, 795, 612, 1170, 1701, 873, 1137, 1044, 852, 1278, 807, 1122, 1068, 1038, 2145, 525, 624, 597, 1065, 2226, 1932, 2709, 1047, 1860, 510, 846, 489, 1497, 519, 1035, 1494, 465, 1335, 1350, 3306, 681, 729, 3099, 720, 1200, 1713, 915, 1833, 1374, 2064, 408, 441, 714, 1389, 750, 786, 696, 1110, 1203, 2052, 1473, 1209, 1422, 330, 1797, 1017, 807, 1356, 444, 978, 1917, 477, 582, 585, 951, 456, 1425, 891, 741, 744, 843, 1290, 2124, 1137, 777, 270, 768, 453, 474, 972, 522, 1284, 606, 1440, 2193, 489, 489, 1257, 465, 645, 1350, 426, 348, 3486, 588, 825, 558, 507, 510, 1338, 1593, 1410, 219, 828, 855, 1284, 1347, 1635, 1332, 2289, 606, 1281, 888, 1227, 1392, 645, 627, 747, 339, 432, 348, 258, 204, 1299, 1803, 423, 831, 837, 414, 246, 438, 888, 1173, 504, 885, 297, 435, 2121, 330, 366, 372, 279, 867, 1323, 477, 1110, 930, 654, 267, 789, 1050, 1077, 747, 483, 1059, 987, 876, 1503, 648, 939, 1446, 651, 1176, 1563, 1104, 1425, 1632, 1473, 1428, 1170, 1485, 1311, 966, 1431, 306, 756, 1644, 891, 4317, 5430, 1050, 1713, 1725, 2163, 1209, 564, 765, 13029, 471, 324, 699], [99.1, 98.52, 98.81, 98.46, 99.26, 99.24, 98.35, 99.1, 98.32, 99.23, 98.46, 99.33, 99.26, 99.47, 99.72, 99.04, 98.34, 99.42, 99.83, 100.0, 99.73, 99.81, 99.66, 99.31, 98.66, 99.03, 98.82, 99.25, 98.86, 99.06, 88.42, 99.31, 99.03, 99.33, 98.24, 99.22, 99.26, 99.2, 99.16, 99.52, 97.2, 99.43, 98.4, 99.16, 99.53, 98.7, 99.17, 99.19, 98.85, 99.19, 98.82, 98.7, 100.0, 99.53, 99.81, 99.81, 97.95, 100.0, 99.62, 99.7, 99.12, 98.83, 99.59, 99.48, 98.33, 99.33, 99.36, 98.03, 99.07, 99.2, 99.95, 100.0, 99.77, 99.58, 99.42, 99.33, 99.49, 98.85, 99.37, 99.09, 86.72, 99.25, 99.09, 98.94, 99.7, 99.5, 99.61, 99.13, 99.11, 99.1, 98.88, 98.85, 98.74, 99.14, 99.14, 98.95, 99.56, 98.88, 98.65, 99.19, 99.73, 98.93, 99.46, 99.34, 99.74, 99.23, 99.63, 99.35, 98.9, 98.52, 99.9, 100.0, 98.21, 99.83, 99.31, 99.59, 89.66, 96.15, 98.01, 99.78, 99.34, 99.78, 99.53, 99.14, 91.64, 99.32, 98.91, 99.28, 99.21, 97.06, 99.48, 99.25, 99.22, 100.0, 82.25, 98.13, 99.22, 95.63, 85.03, 83.26, 99.26, 98.68, 99.84, 99.66, 99.19, 99.93, 98.76, 97.77, 99.47, 99.7, 99.31, 99.14, 99.61, 98.04, 99.08, 99.28, 99.29, 98.8, 99.52, 98.31, 97.15, 98.4, 97.3, 99.49, 99.21, 98.98, 99.66, 99.31, 99.01, 99.09, 98.36, 98.92, 99.64, 99.42, 99.47, 99.37, 98.03, 99.14, 99.39, 100.0, 99.11, 98.86, 99.63, 99.33, 98.76, 96.69, 99.39, 98.97, 98.87, 97.84, 98.72, 99.45, 99.69, 99.49, 99.62, 99.73, 99.51, 99.69, 99.66, 99.65, 99.66, 99.73, 99.85, 99.28, 99.02, 99.67, 99.34, 99.21, 98.99, 98.93, 98.78, 98.86, 98.83, 99.01, 99.26, 98.43, 97.69, 98.56, 99.08, 98.73, 98.15, 98.28], [100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 98.74, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.92, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.91, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.71, 100.0, 100.0, 99.58, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 88.96, 89.78, 100.0, 100.0, 93.33, 100.0, 100.0, 100.0, 99.6, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.78, 99.82, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 99.04, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 98.87, 100.0, 100.0, 100.0, 99.85, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0], ['contig00001', 'contig00001', 'contig00001', 'contig00001', 'contig00001', 'contig00002', 'contig00002', 'contig00002', 'contig00002', 'contig00002', 'contig00002', 'contig00002', 'contig00002', 'contig00002', 'contig00002', 'contig00002', 'contig00002', 'contig00003', 'contig00003', 'contig00003', 'contig00003', 'contig00003', 'contig00003', 'contig00003', 'contig00003', 'contig00003', 'contig00003', 'contig00003', 'contig00003', 'contig00004', 'contig00004', 'contig00004', 'contig00006', 'contig00007', 'contig00007', 'contig00007', 'contig00007', 'contig00007', 'contig00007', 'contig00007', 'contig00007', 'contig00007', 'contig00007', 'contig00007', 'contig00007', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00008', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00009', 'contig00010', 'contig00011', 'contig00011', 'contig00011', 'contig00011', 'contig00011', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00012', 'contig00013', 'contig00014', 'contig00015', 'contig00015', 'contig00015', 'contig00015', 'contig00017', 'contig00018', 'contig00020', 'contig00020', 'contig00020', 'contig00020', 'contig00020', 'contig00020', 'contig00020', 'contig00020', 'contig00020', 'contig00020', 'contig00021', 'contig00021', 'contig00021', 'contig00021', 'contig00021', 'contig00021', 'contig00021', 'contig00021', 'contig00021', 'contig00023', 'contig00023', 'contig00023', 'contig00023', 'contig00025', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00026', 'contig00031', 'contig00031', 'contig00031', 'contig00031', 'contig00032', 'contig00032', 'contig00032', 'contig00032', 'contig00032', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00034', 'contig00038', 'contig00038', 'contig00038', 'contig00038', 'contig00038', 'contig00038', 'contig00038', 'contig00038', 'contig00038', 'contig00038', 'contig00038', 'contig00038', 'contig00040', 'contig00040', 'contig00040', 'contig00042', 'contig00042', 'contig00042'], [995, 300061, 543082, 637876, 719479, 529674, 530200, 531345, 532343, 533044, 533430, 533955, 534406, 535623, 537351, 538063, 549144, 175475, 176687, 188546, 189000, 189416, 190037, 192146, 193033, 200456, 201484, 201998, 202868, 183546, 273868, 276796, 186881, 16123, 17186, 61995, 86039, 86842, 87960, 89024, 133918, 136116, 136637, 137257, 137853, 165366, 170312, 172290, 174991, 176001, 177857, 178368, 179381, 179945, 181454, 182061, 183463, 185019, 185499, 186840, 188411, 191716, 192406, 193142, 196237, 196956, 198148, 199922, 214386, 222359, 25709, 123088, 123501, 123954, 124695, 126300, 127096, 127927, 128634, 129754, 130975, 149903, 151488, 152701, 154363, 154715, 156517, 157535, 158331, 159700, 184403, 202891, 34430, 90914, 91527, 92120, 93067, 93562, 49066, 49969, 55704, 56444, 57425, 58798, 63766, 64905, 65681, 65995, 66759, 67213, 67714, 68693, 69458, 81378, 76162, 17983, 109, 633, 36613, 67746, 1, 128588, 107455, 107877, 108226, 111729, 112313, 113134, 113682, 114294, 116078, 117430, 9337, 10824, 51452, 52347, 53230, 54536, 56096, 64239, 65693, 109802, 111437, 112783, 118943, 61778, 42362, 42985, 43614, 44357, 44695, 45123, 45473, 45733, 45899, 47199, 49001, 49457, 50385, 51519, 51941, 52195, 52758, 53657, 54810, 55325, 56219, 56543, 56974, 59091, 59425, 59787, 60145, 60404, 61461, 62780, 63244, 64359, 65285, 65941, 66204, 66989, 6474, 7555, 13445, 14744, 46066, 47070, 47997, 49492, 50243, 12034, 13676, 14399, 15589, 17393, 18500, 19937, 21589, 23058, 24499, 25751, 27375, 44551, 42086, 43513, 43818, 44570, 46443, 47527, 51840, 57266, 58312, 60021, 61837, 67129, 37469, 38675, 39513, 16686, 17211, 17679], [1999, 300330, 543840, 639372, 720831, 530198, 531348, 532346, 533047, 533433, 533948, 534401, 535623, 537131, 538058, 540039, 551918, 176509, 177835, 188953, 189365, 189952, 192085, 193021, 200463, 201487, 201990, 202792, 203479, 184715, 275568, 277668, 188016, 17166, 18037, 63272, 86845, 87963, 89027, 90061, 136062, 136640, 137260, 137853, 138917, 167591, 172243, 174998, 176037, 177860, 178366, 179213, 179869, 181441, 181972, 183095, 184974, 185483, 186833, 188189, 191719, 192396, 193134, 196240, 196956, 198155, 199860, 200836, 216218, 223732, 27772, 123495, 123941, 124667, 126083, 127049, 127881, 128622, 129743, 130956, 133023, 151375, 152696, 154116, 154692, 156511, 157533, 158341, 159686, 160143, 185380, 204807, 34906, 91495, 92111, 93070, 93522, 94986, 49956, 50709, 56447, 57286, 58714, 60921, 64902, 65681, 65950, 66762, 67211, 67686, 68685, 69214, 70741, 81983, 77601, 20175, 543, 1071, 37869, 68210, 602, 129937, 107880, 108224, 111717, 112316, 113137, 113691, 114188, 114803, 117415, 119022, 10746, 11042, 52279, 53201, 54513, 55882, 57742, 65570, 67981, 110407, 112717, 113670, 120169, 63169, 43006, 43605, 44360, 44695, 45126, 45470, 45730, 45936, 47197, 49001, 49423, 50287, 51221, 51932, 52186, 52632, 53645, 54829, 55316, 56209, 56515, 56977, 59094, 59420, 59790, 60158, 60423, 61270, 62783, 63256, 64362, 65288, 65938, 66207, 66992, 68038, 7550, 8301, 13927, 15790, 47052, 47945, 49499, 50138, 51181, 13479, 14326, 15574, 17151, 18496, 19924, 21568, 23061, 24485, 25668, 27235, 28685, 45516, 43516, 43818, 44573, 46213, 47333, 51843, 57269, 58315, 60024, 61745, 63999, 68337, 38032, 39439, 52541, 17156, 17534, 18377], ['+', '-', '+', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-', '+', '+', '-', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '-', '-', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '-', '-', '-', '+', '+', '+', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '+', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '+', '+', '+', '-', '-', '-', '+', '+', '+', '-', '-', '-', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '+', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', '+', '-', '-', '-', '-', '+', '+', '+', '+', '+', '+', '+', '-', '-', '+', '+', '-', '-', '-'], [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], ['NP_252898', 'NP_252722', 'NP_252494', 'NP_252413', 'NP_252339', 'NP_251785', 'NP_251786', 'NP_251787', 'NP_251788', 'NP_251789', 'NP_251790', 'NP_251791', 'NP_251792', 'NP_251793', 'NP_251794', 'NP_251795', 'NP_251805', 'NP_249086', 'NP_249087', 'NP_249099', 'NP_249100', 'NP_249101', 'NP_249102', 'NP_249103', 'NP_249104', 'NP_249105', 'NP_249106', 'NP_249107', 'NP_249108', 'NP_253136', 'NP_253216', 'NP_253218', 'NP_250881', 'NP_253640', 'NP_253641', 'NP_253675', 'NP_253696', 'NP_253697', 'NP_253698', 'NP_253699', 'NP_253727', 'NP_253728', 'NP_253729', 'NP_253730', 'NP_253731', 'NP_248785', 'NP_248781', 'NP_248780', 'NP_248779', 'NP_248778', 'NP_248777', 'NP_248776', 'NP_248775', 'NP_248774', 'NP_248773', 'NP_248772', 'NP_248771', 'NP_248770', 'NP_248769', 'NP_248768', 'NP_248767', 'NP_248766', 'NP_248765', 'NP_248764', 'NP_248763', 'NP_248762', 'NP_248761', 'NP_248760', 'NP_248741', 'NP_248734', 'AAC16023', 'NP_249768', 'NP_249769', 'NP_249770', 'NP_249771', 'NP_249772', 'NP_249773', 'NP_249774', 'NP_249775', 'NP_249776', 'NP_249777', 'NP_249788', 'NP_249789', 'NP_249790', 'NP_249791', 'NP_249792', 'NP_249793', 'NP_249794', 'NP_249795', 'NP_249796', 'NP_249821', 'NP_249839', 'NP_251392', 'NP_249453', 'NP_249454', 'NP_249455', 'NP_249456', 'NP_249457', 'NP_250152', 'NP_250151', 'NP_250146', 'NP_250145', 'NP_250144', 'NP_250143', 'NP_250140', 'NP_250139', 'NP_250138', 'NP_250137', 'NP_250136', 'NP_250135', 'NP_250134', 'NP_250133', 'NP_250132', 'NP_250123', 'NP_249940', 'NP_249535', 'NP_252900', 'NP_252899', 'NP_250562', 'NP_250535', 'NP_252906', 'NP_254170', 'NP_253246', 'NP_253245', 'NP_253244', 'NP_253243', 'NP_253242', 'NP_253241', 'NP_253240', 'NP_253239', 'NP_253237', 'NP_253236', 'NP_251103', 'NP_251102', 'NP_251086', 'NP_251085', 'NP_251084', 'NP_251083', 'NP_251082', 'NP_251076', 'NP_251075', 'NP_252166', 'NP_252168', 'NP_252169', 'NP_252174', 'NP_254009', 'NP_250416', 'NP_250415', 'NP_250414', 'NP_250413', 'NP_250412', 'NP_250411', 'NP_250410', 'NP_250409', 'NP_250408', 'NP_250407', 'NP_250406', 'NP_250405', 'NP_250404', 'NP_250403', 'NP_250402', 'NP_250401', 'NP_250400', 'NP_250399', 'NP_250398', 'NP_250397', 'NP_250396', 'NP_250395', 'NP_250394', 'NP_250393', 'NP_250392', 'NP_250391', 'NP_250390', 'NP_250389', 'NP_250388', 'NP_250387', 'NP_250386', 'NP_250385', 'NP_250384', 'NP_250383', 'NP_250382', 'NP_250381', 'NP_253949', 'NP_253948', 'NP_253942', 'NP_253940', 'NP_250944', 'NP_250945', 'NP_250946', 'NP_250947', 'NP_250948', 'NP_252241', 'NP_252240', 'NP_252239', 'NP_252238', 'NP_252237', 'NP_252236', 'NP_252235', 'NP_252234', 'NP_252233', 'NP_252232', 'NP_252231', 'NP_252230', 'NP_252216', 'NP_252921', 'NP_252920', 'NP_252919', 'NP_252918', 'NP_252917', 'NP_252916', 'NP_252915', 'NP_252914', 'NP_252913', 'NP_252912', 'NP_252911', 'NP_252907', 'NP_251116', 'NP_251115', 'NP_251114', 'NP_252042', 'NP_252041', 'NP_252040']]}
{'type': 'table', 'title': 'Plasmid typing', 'header': ['Plasmid', 'Gene length', 'Identity %', 'Coverage %', 'Contig', 'Start in contig', 'End in contig', 'Strand', 'Incompatibility group', 'Accession number'], 'values': [[], [], [], [], [], [], [], [], [], []]}

[None, None, None]

In [10]:
## Create a structured dataframe with the results of the analysis
# df = pd.DataFrame.from_dict(reports[0]["sections"][2]["data"][0])

df = pd.DataFrame(reports[0]["sections"][2]["data"][0]["values"], index=reports[0]["sections"][2]["data"][0]["header"])
df

,0,1,2,3,4,5,6,7,8,9
Resistance gene,aadA13,ant(2'')-Ia,aph(3')-IIb,blaOXA-488,blaPAO,catB7,crpP,fosA,qacE,sul1
Gene length,798,534,807,789,1194,639,198,408,278,840
Identity %,100.0,100.0,98.76,99.87,99.25,98.75,98.48,99.02,100.0,100.0
Coverage %,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,83.48,100.0
Contig,contig00086,contig00102,contig00001,contig00039,contig00001,contig00033,contig00056,contig00009,contig00139,contig00080
Start in contig,133,133,169523,19349,182685,25811,3829,183999,1,733
End in contig,930,666,170329,20137,183878,26449,4026,184406,278,1572
Strand,-,-,+,+,-,+,+,+,-,-
Target antibiotic,streptomycin,gentamicin,kanamycin,ampicillin,"ampicillin,amoxicillin/clavulanicacid,cefoxiti...",chloramphenicol,ciprofloxacinI/R,fosfomycin,unknown[qacE_1_X68232],sulfisoxazole
Accession number,AY713504,X04555,CP006832,CP017969,AY083592,AF036933,HM560971,ACWU01000146,X68232,U12338

In [13]:
## Understand what is in the report, normally there is only one analysis but many ANTIMICROBIAL RESISTANCE ANALYSIS are
## available. There is maybe multiple strain of bacterias in the analysed sample.

In [11]:
## Checking out the ORGANISM IDENTIFICATION category find out if there is multiple species of bacterias in the sample 
## 26 different bacterias present in the sample

df = pd.DataFrame(reports[0]["sections"][3]["data"][0]["values"], index=reports[0]["sections"][3]["data"][0]["header"])
df

,0,1,2,3,4,5,6,7,8,9,...,69,70,71,72,73,74,75,76,77,78
Species name,Pseudomonas aeruginosa,Pseudomonas sp. 13159349,Pseudomonas putida,Pseudomonas stutzeri,Pseudomonas protegens,Pseudomonas phage MD8,Pseudomonas sp. PS1(2021),Pseudomonas sp. FDAARGOS 761,Stenotrophomonas maltophilia,Pseudomonas phage JBD30,...,Pseudomonas campi,Pseudomonas sp. p1(2021b),Pseudomonas sp. CC6-YY-74,Bordetella genomosp. 6,Cutibacterium acnes,Pseudomonas sp. ABC1,Pseudomonas balearica,Runella slithyformis,Pseudomonas fulva,Pseudomonas synxantha
NCBI ID,287,2662034,303,316,380021,1868596,2866282,2545800,40324,1223260,...,2731681,2874628,1930532,463024,1747,2748080,74829,106,47880,47883
Fraction of reads,0.98642,0.00328,0.00282,0.00196,0.00102,0.00059,0.00053,0.00044,0.0004,0.00036,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
## Create a small handmade ttl graph using the previous antibiotic resistance data + the metadata uploaded to ABRomics
## (which is at the start of the report category 0)
## Graph with only one analysis

In [13]:
# Placeholder nmespaces
ABROMICS = Namespace("http://www.abromics.org/ontology/")
SOSA = Namespace('http://www.w3.org/ns/sosa/')
NCIt = Namespace('http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl/')
OHMI = Namespace('https://bioportal.bioontology.org/ontologies/OHMI/')
ARO = Namespace('https://bioportal.bioontology.org/ontologies/ARO/')
GO = Namespace('https://bioportal.bioontology.org/ontologies/GO/')


g = Graph()

## Sample metadata
sampleMetadata = reports[0]["sections"][0]["data"][0]["values"]
sampleMetadata

## Storing the sample
sampleId = uuid.uuid1()
g.add((ABROMICS[str(sampleId)], RDF.type, SOSA.ObservableProperty))
g.add((ABROMICS[str(sampleId)], ABROMICS.MicroOrganism, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][1]).replace(' ', '_')]))
g.add((ABROMICS[str(sampleId)], ABROMICS.CollectedAt, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][2])]))
g.add((ABROMICS[str(sampleId)], ABROMICS.Source, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][3])]))
g.add((ABROMICS[str(sampleId)], ABROMICS.SampleType, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][4])]))
g.add((ABROMICS[str(sampleId)], ABROMICS.Host, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][5]).replace(' ', '_')]))
g.add((ABROMICS[str(sampleId)], ABROMICS.Location, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][6])]))
g.add((ABROMICS[str(sampleId)], ABROMICS.SequencingTechnology, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][7]).replace(' ', '_')]))
g.add((ABROMICS[str(sampleId)], ABROMICS.SequencingPlatform, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][8]).replace(' ', '_')]))
g.add((ABROMICS[str(sampleId)], ABROMICS.SubmitterName, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][9]).replace(' ', '_')]))
g.add((ABROMICS[str(sampleId)], ABROMICS.SubmitterEmail, ABROMICS[str(reports[0]["sections"][0]["data"][0]["values"][10]).replace(' ', '_')]))

## Storing the analysis
analysisId = uuid.uuid1()
g.add((ABROMICS[str(analysisId)], RDF.type, SOSA.Observation))
g.add((ABROMICS[str(analysisId)], SOSA.ObservedProperty, ABROMICS[str(sampleId)]))

## Storing the FeatureOfInterest
featureOfInterestId = uuid.uuid1()
g.add((ABROMICS[str(featureOfInterestId)], SOSA.isFeatureOfInterest, ABROMICS[str(analysisId)]))
g.add((ABROMICS[str(featureOfInterestId)], RDF.type, SOSA.FeatureOfInterest))
g.add((ABROMICS[str(featureOfInterestId)], RDF.type, ABROMICS.Genomic))

## Storing the Microbiome
microbiomeId = uuid.uuid1()
g.add((ABROMICS[str(microbiomeId)], RDF.type, OHMI.HumanMicrobiome))
g.add((ABROMICS[str(featureOfInterestId)], ABROMICS.has, ABROMICS[str(microbiomeId)]))

## Store a single strain observed in the sample
strainId = uuid.uuid1()
g.add((ABROMICS[str(strainId)], RDF.type, ARO.Strain))
g.add((ABROMICS[str(microbiomeId)], ABROMICS.contains, ABROMICS[str(strainId)]))
g.add((ABROMICS[str(strainId)], ABROMICS.MLSTProfile, Literal("MLST_profile", datatype=XSD.string)))
g.add((ABROMICS[str(strainId)], ABROMICS.STProfile, Literal("ST_profile", datatype=XSD.string)))

## Store a molecule the strain is resistant to
moleculeId = uuid.uuid1()
g.add((ABROMICS[str(moleculeId)], RDF.type, ARO.Molecule))
g.add((ABROMICS[str(strainId)], ABROMICS.isResistantTo, ABROMICS[str(moleculeId)]))
g.add((ABROMICS[str(moleculeId)], RDFS.label, Literal(str(reports[0]["sections"][2]["data"][0]["values"][8][0]), datatype=XSD.string))) ## store the name of the molecule


## Store the resistance gene associated with the molecule the bacteria is resistant to
geneId = uuid.uuid1()
g.add((ABROMICS[str(geneId)], RDF.type, GO.Gene))
g.add((ABROMICS[str(geneId)], ABROMICS.givesResistanceTo, ABROMICS[str(moleculeId)]))


g.serialize(destination="../graph/antibiotic-resistance.ttl",format='ttl')

In [ ]:
## Issues of the graph: 
## A microbiome can't be an observed property as the sample is already one, it makes the graph confusing. A new abromics relation should be created to link 
## a FeatureOfInterest to the OHMI:Microbiome class

In [18]:
## Use their sparql endpoint https://www.bgee.org/support/tutorial-query-bgee-knowledge-graph-sparql (intergate their data to the graph)
## Maybe also the NCBI one too
## + UBERON